name: Deploy to cPanel

on:
 push:
  branches:
    - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup Node.js environment
    uses: actions/setup-node@v2
    with:
      node-version: '18'

  - name: Install dependencies and build
    run: |
      cd client
      npm install
      npm run build

  - name: Deploy via FTP
    run: |
      lftp -e "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; set ssl:verify-certificate no; mirror -R -e -x .git/ -x .github/ -x .next/ -x node_modules/