name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Install dependencies and build Next.js app
        run: |
          cd client
          npm install
          npm run build

      - name: Install lftp
        run: sudo apt install lftp

      - name: Configure lftp
        run: |
          mkdir ~/.lftp
          echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

      - name: Load Secrets
        run: |
          echo "machine ${{ secrets.FTP_HOST }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc

      - name: Upload contents of dist folder
        run: |
          lftp -e "mirror --only-newer --parallel=100 -R ./client/_next/ /drawing.shubhamlal.in/" ${{ secrets.FTP_HOST }}